receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
  filter:
    error_mode: ignore
    traces:
      span:
        - 'resource.attributes["service.name"] == "jaeger-all-in-one"'
        - 'resource.attributes["service.name"] == "jaeger-query"'

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter, spanmetrics, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
