# Generated by Django 5.2.8 on 2025-12-07 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('local', 'Local Model'), ('google', 'Google AI')], max_length=20)),
                ('api_key_encrypted', models.CharField(max_length=500)),
                ('model_name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('supports_question_generation', models.BooleanField(default=True)),
                ('supports_feedback_analysis', models.BooleanField(default=True)),
                ('supports_transcription', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('additional_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_type'], name='interviews__provide_f4605a_idx'), models.Index(fields=['is_active'], name='interviews__is_acti_3e2e11_idx'), models.Index(fields=['is_default'], name='interviews__is_defa_1b46a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveInterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting for Participants'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('enable_realtime_feedback', models.BooleanField(default=True)),
                ('feedback_visibility', models.CharField(choices=[('interviewer_only', 'Interviewer Only'), ('both', 'Both Parties'), ('none', 'No Real-time Feedback')], default='interviewer_only', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('room_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('full_audio_url', models.URLField(blank=True, max_length=500)),
                ('full_video_url', models.URLField(blank=True, max_length=500)),
                ('interviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_interviews', to='interviews.userprofile')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to='interviews.userprofile')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_interviews', to='interviews.jobrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveInterviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('interviewer', 'Interviewer Report'), ('candidate', 'Candidate Report')], max_length=20)),
                ('overall_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('behavioral_score', models.FloatField(default=0)),
                ('mindset_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('key_strengths', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('hiring_recommendation', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No')], max_length=20)),
                ('interviewer_comments', models.TextField(blank=True)),
                ('report_pdf_url', models.URLField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interviews.liveinterviewsession')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveInterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('question_category', models.CharField(max_length=50)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('custom_question', models.BooleanField(default=False)),
                ('expected_topics', models.JSONField(default=list)),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question_audio_url', models.URLField(blank=True, max_length=500)),
                ('answer_audio_url', models.URLField(blank=True, max_length=500)),
                ('answer_transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.liveinterviewsession')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='SpeechProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('provider_type', models.CharField(choices=[('openai_whisper', 'OpenAI Whisper'), ('assemblyai', 'AssemblyAI'), ('google_cloud', 'Google Cloud Speech')], max_length=20)),
                ('service_type', models.CharField(choices=[('stt', 'Speech-to-Text'), ('tts', 'Text-to-Speech'), ('both', 'Both STT and TTS')], max_length=10)),
                ('api_key_encrypted', models.CharField(blank=True, max_length=500)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('language_support', models.JSONField(default=list)),
                ('additional_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_stt', models.BooleanField(default=False)),
                ('is_default_tts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_type'], name='interviews__provide_5c908f_idx'), models.Index(fields=['service_type'], name='interviews__service_e76572_idx'), models.Index(fields=['is_active'], name='interviews__is_acti_619e05_idx'), models.Index(fields=['is_default_stt'], name='interviews__is_defa_2cdc87_idx'), models.Index(fields=['is_default_tts'], name='interviews__is_defa_46fa2c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='liveinterviewsession',
            index=models.Index(fields=['interviewer', 'status'], name='interviews__intervi_4edcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewsession',
            index=models.Index(fields=['candidate', 'status'], name='interviews__candida_45accf_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewsession',
            index=models.Index(fields=['status'], name='interviews__status_af7d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewsession',
            index=models.Index(fields=['scheduled_at'], name='interviews__schedul_1d8a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewsession',
            index=models.Index(fields=['created_at'], name='interviews__created_81d9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewreport',
            index=models.Index(fields=['live_session', 'report_type'], name='interviews__live_se_12dd56_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewreport',
            index=models.Index(fields=['generated_at'], name='interviews__generat_e12109_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewreport',
            index=models.Index(fields=['overall_score'], name='interviews__overall_1057a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liveinterviewreport',
            unique_together={('live_session', 'report_type')},
        ),
        migrations.AddIndex(
            model_name='liveinterviewquestion',
            index=models.Index(fields=['live_session', 'question_number'], name='interviews__live_se_f32723_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewquestion',
            index=models.Index(fields=['question_category'], name='interviews__questio_a69d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='liveinterviewquestion',
            index=models.Index(fields=['asked_at'], name='interviews__asked_a_5ec3cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liveinterviewquestion',
            unique_together={('live_session', 'question_number')},
        ),
    ]
