# Generated by Django 5.2.8 on 2025-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_aiprovider_liveinterviewsession_liveinterviewreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('organization_admin', 'Organization Admin'), ('interviewer', 'Interviewer'), ('candidate', 'Candidate')], max_length=20),
        ),
    ]
