"""
Django settings for interview_service project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(k^k%4lm&n8-&84w$j5uzhm-=y+%ox#oe!-xgb4hjcb^zy3818'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if os.getenv('ALLOWED_HOSTS') else ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be before django.contrib.staticfiles for Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'channels',
    'drf_spectacular',
    'drf_spectacular_sidecar',

    # Local apps
    'interviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'interview_service.urls'

# Django Channels Configuration
ASGI_APPLICATION = 'interview_service.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.getenv('REDIS_HOST', 'redis'), 6379)],
        },
    },
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'interviews.authentication.JWTAuthenticationFromAuthService',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    }
}

# DRF Spectacular Settings (API Documentation)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Interview Service API',
    'DESCRIPTION': 'AI-powered interview practice and live interview platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'interview_service.wsgi.application'

# JWT Authentication Configuration
# CRITICAL: JWT_SIGNING_KEY must be set in .env and must match auth_service exactly!
JWT_SIGNING_KEY = os.getenv('JWT_SIGNING_KEY')
if not JWT_SIGNING_KEY:
    raise ValueError(
        "JWT_SIGNING_KEY environment variable is required! "
        "Set it in .env to match the auth_service JWT signing key."
    )
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_ACCESS_TOKEN_LIFETIME = int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 3600))  # 1 hour in seconds


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('INTERVIEW_DB_NAME'),
        'USER': config('INTERVIEW_USER'),
        'PASSWORD': config('INTERVIEW_PASSWORD'),
        'HOST': config('INTERVIEW_HOST'),
        'PORT': config('INTERVIEW_PORT', cast=int),
    }
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_TASK_ROUTES = {
    'interviews.tasks.generate_interview_questions': {'queue': 'ai_queue'},
    'interviews.tasks.analyze_answer_feedback': {'queue': 'ai_queue'},
    'interviews.tasks.generate_session_report': {'queue': 'ai_queue'},
    'interviews.tasks.generate_followup_question': {'queue': 'ai_queue'},
    'interviews.tasks.process_answer_audio': {'queue': 'audio_queue'},
    'interviews.tasks.merge_session_audio': {'queue': 'audio_queue'},
    'interviews.tasks.update_user_progress': {'queue': 'interview_queue'},
    'interviews.tasks.publish_session_events': {'queue': 'interview_queue'},
}

# MinIO Configuration (Object Storage)
MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT', 'minio:9000')  # Internal endpoint for service-to-service communication
MINIO_PUBLIC_ENDPOINT = os.getenv('MINIO_PUBLIC_ENDPOINT', 'localhost:9000')  # Public endpoint for browser access
MINIO_ACCESS_KEY = os.getenv('MINIO_ROOT_USER', 'minioadmin')
MINIO_SECRET_KEY = os.getenv('MINIO_ROOT_PASSWORD', 'minioadmin')
MINIO_SECURE = os.getenv('MINIO_SECURE', 'False') == 'True'
MINIO_BUCKET_PROFILES = os.getenv('MINIO_BUCKET_PROFILES', 'user-profiles')
MINIO_BUCKET_DOCUMENTS = os.getenv('MINIO_BUCKET_DOCUMENTS', 'user-documents')
MINIO_BUCKET_AUDIO = os.getenv('MINIO_BUCKET_AUDIO', 'interview-audio')
MINIO_BUCKET_RECORDINGS = os.getenv('MINIO_BUCKET_RECORDINGS', 'interview-recordings')
MINIO_BUCKET_TEMP = os.getenv('MINIO_BUCKET_TEMP', 'temporary-files')

# AI Provider Defaults
DEFAULT_AI_PROVIDER = os.getenv('DEFAULT_AI_PROVIDER', 'openai')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-3.5-turbo')
OPENAI_TEMPERATURE = float(os.getenv('OPENAI_TEMPERATURE', '0.7'))
OPENAI_MAX_TOKENS = int(os.getenv('OPENAI_MAX_TOKENS', '2000'))

# Speech Provider Defaults
DEFAULT_STT_PROVIDER = os.getenv('DEFAULT_STT_PROVIDER', 'whisper')
DEFAULT_TTS_PROVIDER = os.getenv('DEFAULT_TTS_PROVIDER', 'openai')
ASSEMBLYAI_API_KEY = os.getenv('ASSEMBLYAI_API_KEY', '')
GOOGLE_CLOUD_PROJECT = os.getenv('GOOGLE_CLOUD_PROJECT', '')

# API Key Encryption (for storing provider API keys)
FERNET_KEY = os.getenv('FERNET_KEY', '')  # Generate with: from cryptography.fernet import Fernet; Fernet.generate_key()

# File Upload Settings
MAX_UPLOAD_SIZE_MB = int(os.getenv('MAX_UPLOAD_SIZE_MB', '10'))
MAX_UPLOAD_SIZE_BYTES = MAX_UPLOAD_SIZE_MB * 1024 * 1024
ALLOWED_AUDIO_FORMATS = ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/webm']
ALLOWED_IMAGE_FORMATS = ['image/jpeg', 'image/png', 'image/gif']
ALLOWED_DOCUMENT_FORMATS = ['application/pdf']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration

import sys
sys.path.insert(0, os.path.join(BASE_DIR.parent, 'common'))

try:
    from logging_config import get_logging_config
    LOGGING = get_logging_config('interview_service', log_level='DEBUG' if DEBUG else 'INFO')
except ImportError:
    # Fallback if common module is not available
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }
